name: "Build Wheels"

on:
  push:
    branches:
    - main
    tags:
    - 'v*.*.*'

jobs:
  buildpackage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install wheel and SDist requirements
      run: python -m pip install "setuptools>=42.0" wheel twine

    - name: Build SDist
      run: python setup.py sdist bdist_wheel

    - uses: actions/upload-artifact@v4
      with:
        path: |
            dist/*.tar.gz
            dist/*.whl

  publish:
    needs: [buildpackage]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    permissions:
      id-token: write

    environment: release

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.12.4
